language: node_js

node_js:
  - 18

services:
  - docker

script:
  - echo "Build started"

after_success:
  - docker build -t tainaraalvessilva/udagram-api ./udagram-api
  - docker build -t tainaraalvessilva/udagram-frontend ./udagram-frontend
