apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBVkZLRkJIWkxQTERGUUhNQgphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSB0UHphTFRySmNDRi9nV3VDajk4NjN2cDdicFJhM0VrZ0tJNEJtTkNGCg==